# GSE169246

In [ ]:
import pandas as pd
import scanpy as sc
import os
import anndata
from scipy.io import mmread

In [5]:
##手动读入
path = "./raw/GSE169246/suppl/RNA"
prefix = "GSE169246_TNBC_RNA."

X = mmread(f"{path}/{prefix}matrix.mtx.gz").T.tocsr()

barcodes = pd.read_csv(f"{path}/{prefix}barcods.tsv.gz",header=None)[0].astype(str)

features = pd.read_csv(f"{path}/{prefix}features.tsv.gz",sep="\t",header=None)

gene_names = features[0].astype(str)

adata = sc.AnnData(X)
adata.obs_names = barcodes
adata.var_names = gene_names
adata.var_names_make_unique()

adata

AnnData object with n_obs × n_vars = 489490 × 27085

In [6]:
adata.obs_names

Index(['AAACCTGAGGTTACCT.Pre_P007_b', 'AAACCTGCAAAGGAAG.Pre_P007_b',
       'AAACCTGCAAGTCTAC.Pre_P007_b', 'AAACCTGCAATAAGCA.Pre_P007_b',
       'AAACCTGCACAGCGTC.Pre_P007_b', 'AAACCTGCAGCTATTG.Pre_P007_b',
       'AAACCTGCAGTCCTTC.Pre_P007_b', 'AAACCTGGTAATCACC.Pre_P007_b',
       'AAACCTGGTAGTAGTA.Pre_P007_b', 'AAACCTGGTCAGAGGT.Pre_P007_b',
       ...
       'TGCGCAGCAGAGTGTG.Pre_P004_t', 'TGCGTGGGTAGCGTAG.Pre_P004_t',
       'TGCTACCTCTCTTATG.Pre_P004_t', 'TGCTGCTTCAGGCCCA.Pre_P004_t',
       'TGGCGCATCCCATTTA.Pre_P004_t', 'TGGTTAGTCACTCTTA.Pre_P004_t',
       'TGTTCCGTCTAACGGT.Pre_P004_t', 'TTCGAAGCAATCCAAC.Pre_P004_t',
       'TTCTCAATCATCATTC.Pre_P004_t', 'TTCTTAGAGAAGCCCA.Pre_P004_t'],
      dtype='object', length=489490)

In [18]:
# adata.obs['sample'] = adata.obs.index.str.split('.').str[-1].str.rsplit('_', n=1).str[0]
adata.obs['sample'] = adata.obs.index.str.split('_').str[-2]
adata

AnnData object with n_obs × n_vars = 489490 × 27085
    obs: 'sample', 'dataset', 'symptoms', 'gender', 'species', 'age', 'intervention', 'location'

In [19]:
adata.obs['sample'].value_counts()

sample
P019    53404
P013    45746
P025    33268
P023    30415
P007    30407
P002    29952
P004    26086
P016    25249
P010    22999
P022    22128
P012    20917
P020    20757
P005    19534
P008    19347
P024    16005
P017    15206
P018    14679
P014    12923
P011    11203
P001     9882
P028     5034
P003     4349
Name: count, dtype: int64

In [20]:
# include dataset column
adata.obs["dataset"] = 'GSE169246'

adata.obs["symptoms"] ='tumor'
adata.obs["gender"] = 'Unknown'
adata.obs["species"] = 'Human'
adata.obs["age"] = 'Unknown'
adata.obs["intervention"] = 'Unknown'
adata.obs["location"] = 'Unknown'
adata

AnnData object with n_obs × n_vars = 489490 × 27085
    obs: 'sample', 'dataset', 'symptoms', 'gender', 'species', 'age', 'intervention', 'location'

In [21]:
adata.write_h5ad("./output_0531/GSE169246/GSE169246_raw.h5ad")
adata

AnnData object with n_obs × n_vars = 489490 × 27085
    obs: 'sample', 'dataset', 'symptoms', 'gender', 'species', 'age', 'intervention', 'location'

# GSE178341

In [22]:
adata = sc.read_10x_h5("./raw/GSE178341/suppl/GSE178341_crc10x_full_c295v4_submit.h5")
adata

/home/lixiangyu/anaconda3/envs/zr_r420/lib/python3.9/site-packages/anndata/_core/anndata.py:1899: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/lixiangyu/anaconda3/envs/zr_r420/lib/python3.9/site-packages/anndata/_core/anndata.py:1899: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 370115 × 43113
    var: 'gene_ids', 'feature_types', 'genome'

In [32]:
adata.obs_names

Index(['C103_T_1_1_0_c1_v2_id-AAACCTGCATGCTAGT',
       'C103_T_1_1_0_c1_v2_id-AAACCTGGTAGCCTAT',
       'C103_T_1_1_0_c1_v2_id-AAACCTGGTTGTCGCG',
       'C103_T_1_1_0_c1_v2_id-AAACCTGTCATGTGGT',
       'C103_T_1_1_0_c1_v2_id-AAACCTGTCCTTGGTC',
       'C103_T_1_1_0_c1_v2_id-AAACCTGTCGGATGTT',
       'C103_T_1_1_0_c1_v2_id-AAACCTGTCGTACGGC',
       'C103_T_1_1_0_c1_v2_id-AAACCTGTCTTGCAAG',
       'C103_T_1_1_0_c1_v2_id-AAACGGGAGACGCACA',
       'C103_T_1_1_0_c1_v2_id-AAACGGGAGAGAACAG',
       ...
       'C173_T_0_0_0_c1_v3_id-TTTGATCTCGTCCTTG',
       'C173_T_0_0_0_c1_v3_id-TTTGGAGAGAATCGCG',
       'C173_T_0_0_0_c1_v3_id-TTTGGAGAGGGCGAGA',
       'C173_T_0_0_0_c1_v3_id-TTTGGAGAGTGATAAC',
       'C173_T_0_0_0_c1_v3_id-TTTGGAGCAGCACGAA',
       'C173_T_0_0_0_c1_v3_id-TTTGGAGTCATCGGGC',
       'C173_T_0_0_0_c1_v3_id-TTTGGAGTCTAGTGTG',
       'C173_T_0_0_0_c1_v3_id-TTTGTTGCAGCAATTC',
       'C173_T_0_0_0_c1_v3_id-TTTGTTGGTTCTGAGT',
       'C173_T_0_0_0_c1_v3_id-TTTGTTGTCGTTCCCA'],
      dtype='object', length=370115)

In [36]:
adata.obs['sample'] = adata.obs.index.str.split('_').str[-2]

In [37]:
adata.obs['sample'].value_counts()

sample
v2    266604
v3    103511
Name: count, dtype: int64

In [38]:
adata.var

                              gene_ids    feature_types               genome
RP11-34P13.3       ENSG00000243485.5_4  Gene Expression  GRCh37_liftover_v28
FAM138A            ENSG00000237613.2_2  Gene Expression  GRCh37_liftover_v28
OR4F5              ENSG00000186092.6_4  Gene Expression  GRCh37_liftover_v28
RP11-34P13.7       ENSG00000238009.6_5  Gene Expression  GRCh37_liftover_v28
RP11-34P13.8       ENSG00000239945.1_5  Gene Expression  GRCh37_liftover_v28
...                                ...              ...                  ...
ADT-TCRgd            TCR-gammadelta-B1  Gene Expression  GRCh37_liftover_v28
ADT-TCRab           TCR-alphabeta-IP26  Gene Expression  GRCh37_liftover_v28
ADT-CD1c                     CD1c-L161  Gene Expression  GRCh37_liftover_v28
ADT-CD141     CD141-Thrombomodulin-M80  Gene Expression  GRCh37_liftover_v28
ADT-HLA-DR                 HLA-DR-L243  Gene Expression  GRCh37_liftover_v28

[43113 rows x 3 columns]

In [39]:
# include dataset column
adata.obs["dataset"] = 'GSE178341'
adata.obs["symptoms"] ='tumor'
adata.obs["gender"] = 'Unknown'
adata.obs["species"] = 'Human'
adata.obs["age"] = 'Unknown'
adata.obs["intervention"] = 'Unknown'
adata.obs["location"] = 'Unknown'
adata

AnnData object with n_obs × n_vars = 370115 × 43113
    obs: 'sample', 'dataset', 'symptoms', 'gender', 'species', 'age', 'intervention', 'location'
    var: 'gene_ids', 'feature_types', 'genome'

In [40]:
adata.write_h5ad("./output_0531/GSE178341/GSE178341_raw.h5ad")

# GSE115978

In [51]:
import pandas as pd
from pathlib import Path

data_dir = Path("./raw/GSE115978/suppl")

# 读表达矩阵：行是 gene，列是 cell
counts_path = data_dir / "GSE115978_counts.csv.gz"
matrix_df = pd.read_csv(counts_path, index_col=0)

# 读细胞注释
anno_path = data_dir / "GSE115978_cell.annotations.csv.gz"
anno_df = pd.read_csv(anno_path)

print("matrix:", matrix_df.shape)
print("anno:", anno_df.shape)
print(matrix_df.iloc[:5, :5])
print(anno_df.head())

matrix: (23686, 7186)
anno: (7186, 7)
          cy78_CD45_neg_1_B04_S496_comb  \
C9orf152                              0
RPS11                               370
ELMO2                                43
CREB3L1                               0
PNMA1                                68

          cy79_p4_CD45_neg_PDL1_neg_E11_S1115_comb  CY88_5_B10_S694_comb  \
C9orf152                                         0                     0
RPS11                                            1                    75
ELMO2                                            0                     2
CREB3L1                                          0                     0
PNMA1                                            0                     1

          cy79_p1_CD45_neg_PDL1_pos_AS_C1_R1_F07_S67_comb  \
C9orf152                                                0
RPS11                                                  15
ELMO2                                                  18
CREB3L1                                                 0
PNMA1                                                   8

          cy78_CD45_neg_3_H06_S762_comb
C9orf152                              0
RPS11                               345
ELMO2                                43
CREB3L1                               0
PNMA1                               103
                                             cells samples cell.types  \
0                    cy78_CD45_neg_1_B04_S496_comb   Mel78        Mal
1         cy79_p4_CD45_neg_PDL1_neg_E11_S1115_comb   Mel79        Mal
2                             CY88_5_B10_S694_comb   Mel88        Mal
3  cy79_p1_CD45_neg_PDL1_pos_AS_C1_R1_F07_S67_comb   Mel79        Mal
4                    cy78_CD45_neg_3_H06_S762_comb   Mel78        Mal

   treatment.group  Cohort  no.of.genes  no.of.reads
0   post.treatment  Tirosh         8258       357919
1  treatment.naive  Tirosh         2047         5727
2   post.treatment  Tirosh         5375       139218
3  treatment.naive  Tirosh         5648        73996
4   post.treatment  Tirosh         7409       380341

In [52]:
# 对齐表达矩阵和注释
anno_df["cells"] = anno_df["cells"].astype(str)
anno_df = anno_df.set_index("cells")

common_cells = matrix_df.columns.intersection(anno_df.index)

matrix_df = matrix_df.loc[:, common_cells]
anno_df = anno_df.loc[common_cells]

print(matrix_df.shape)
print(anno_df.shape)
print(matrix_df.columns.equals(anno_df.index))

(23686, 7186)
(7186, 6)
True

In [54]:
adata = sc.AnnData(X=matrix_df.T)
adata.obs = anno_df.copy()
adata.var_names = matrix_df.index.astype(str)

adata

AnnData object with n_obs × n_vars = 7186 × 23686
    obs: 'samples', 'cell.types', 'treatment.group', 'Cohort', 'no.of.genes', 'no.of.reads'

In [57]:
# 列名里的 . -> _
adata.obs.columns = adata.obs.columns.str.replace(".", "_", regex=False)

# 内容里的 . -> _
for col in adata.obs.select_dtypes(include="object").columns:
    adata.obs[col] = adata.obs[col].str.replace(".", "_", regex=False)

adata.obs.head()

,samples,cell_types,treatment_group,Cohort,no_of_genes,no_of_reads
cy78_CD45_neg_1_B04_S496_comb,Mel78,Mal,post_treatment,Tirosh,8258,357919
cy79_p4_CD45_neg_PDL1_neg_E11_S1115_comb,Mel79,Mal,treatment_naive,Tirosh,2047,5727
CY88_5_B10_S694_comb,Mel88,Mal,post_treatment,Tirosh,5375,139218
cy79_p1_CD45_neg_PDL1_pos_AS_C1_R1_F07_S67_comb,Mel79,Mal,treatment_naive,Tirosh,5648,73996
cy78_CD45_neg_3_H06_S762_comb,Mel78,Mal,post_treatment,Tirosh,7409,380341

In [58]:
# include dataset column
adata.obs["dataset"] = 'GSE115978'
adata.obs["symptoms"] ='tumor'
adata.obs["gender"] = 'Unknown'
adata.obs["species"] = 'Human'
adata.obs["age"] = 'Unknown'
adata.obs["intervention"] = 'Unknown'
adata.obs["location"] = 'Unknown'

In [59]:
adata.write_h5ad("./output_0531/GSE115978/GSE115978_raw.h5ad")

# GSE131928

In [65]:
matrix_df = pd.read_csv("/home/lixiangyu/zr/Annotate/ANNOTATE_new/10_downstream/Infer_hot_cold_tumor_celltype/raw/GSE131928/suppl/GSM3828673_10X_GBM_IDHwt_processed_TPM.tsv.gz", sep="\t")
matrix_df

,GENE,102_1,102_2,102_4,102_5,102_7,102_8,102_10,102_11,102_12,...,126_2_227,126_2_230,126_2_231,126_2_232,126_2_235,126_2_236,126_2_237,126_2_240,126_2_242,126_2_245
0,FAM138A,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,OR4F5,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,RP11-34P13.7,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,RP11-34P13.8,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,RP11-34P13.14,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30309,AL592183.1,0.0,157.678966,0.0,0.0,0.0,0.0,246.00246,0.0,208.94275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30310,AC011841.1,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30311,BX072566.1,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30312,AL354822.1,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,208.94275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30313,BAGE5,0.0,0.000000,0.0,0.0,0.0,0.0,0.00000,0.0,0.00000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
transposed_df = matrix_df.T

In [67]:
# transposed_df.index = transposed_df.index.str.replace('.1', '', regex=False)
# 提取基因名和细胞名
cells = transposed_df.index.tolist()
genes = transposed_df.columns.tolist()
matrix_data = transposed_df.iloc[:, :].values
adata = anndata.AnnData(X = matrix_data)
adata.var_names = genes
adata.obs_names = cells
adata

/home/lixiangyu/anaconda3/envs/zr_r420/lib/python3.9/site-packages/anndata/_core/anndata.py:947: UserWarning:
AnnData expects .var.index to contain strings, but got values like:
    [0, 1, 2, 3, 4]

    Inferred to be: integer

  names = self._prep_dim_index(names, "var")

AnnData object with n_obs × n_vars = 16202 × 30314

In [68]:
# include dataset column
adata.obs["dataset"] = 'GSE131928'
adata.obs["symptoms"] ='tumor'
adata.obs["gender"] = 'Unknown'
adata.obs["species"] = 'Human'
adata.obs["age"] = 'Unknown'
adata.obs["intervention"] = 'Unknown'
adata.obs["location"] = 'Unknown'

In [ ]:
adata.write_h5ad("./output_0531/GSE131928/GSE131928_raw.h5ad")